# Generated by Django 5.1 on 2024-08-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(),
        ),
    ]
