# Generated by Django 5.1 on 2024-09-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_appointment_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
    ]
