# Generated by Django 4.2.15 on 2024-08-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("experience", models.IntegerField()),
                ("doctor_details", models.CharField(max_length=200)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctor_photos/"
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_admin.specialization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
