# Generated by Django 5.1 on 2024-09-01 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
