# Generated by Django 5.1 on 2024-09-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_end_time_doctor_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='start_time',
        ),
    ]
