# Generated by Django 4.2.15 on 2024-08-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("custom_admin", "0001_initial"),
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomallotment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
            ),
        ),
    ]
