# Generated by Django 4.2.15 on 2024-08-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patient", "0001_initial"),
        ("custom_admin", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomallotment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="patient.patient"
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="custom_admin.specialization",
            ),
        ),
    ]
